### ISSUE TITLE
Upgrade to BookKeeper 4.5 and ZooKeeper 3.5.3-BETA

### ISSUE THREAD

**Issue by nicoloboschi** [diennea/majordodo#22]
JIRA: https://dev.majordodo.org/jira/browse/MAJ-104

Reporter: eolivelli @eolivelli

We need to upgrade to latest and greatest version of BK.
It comes with the ZK 3.5 dependency, we should upgrade a s well

### Comments from JIRA

---
*Enrico Olivelli* 2017-08-19T16:19:36.000+0200

[~caio] it would be great to update ASAP and include it in next MagNews version 22.09

**Comment by eolivelli** [comment]
closed with 35f5443b9bc0f938d5e379a0b7a534561445df33
