### ISSUE TITLE
Netty: upgrade to 4.1.16.Final

### ISSUE THREAD

**Issue by nicoloboschi** [diennea/majordodo#24]
JIRA: https://dev.majordodo.org/jira/browse/MAJ-102

Reporter: caio @caiok

Netty All: 4.1.12.Final
Netty Native SSL: 2.0.3.Final

Found a bug in 4.1.10: https://github.com/netty/netty/pull/6715

Release notes:
https://netty.io/news/2017/06/09/4-0-48-Final-4-1-12-Final.html

**Comment by eolivelli** [comment]
closed with 35137a10eb36873b3cdd3af916776fb5fc2adef8
